# For local development.

version: "3.8"

services:
  frontend:
    container_name: osakemyrsky-frontend
    build:
      context: ./packages/@osakemyrsky-frontend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      API_URL: http://backend:8080
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/google-application-credentials.json
    ports:
      - 127.0.0.1:8000:8080
    volumes:
      - "./packages/@osakemyrsky-frontend/public:/app/public"
      - "./packages/@osakemyrsky-frontend/styles:/app/styles"
      - "./packages/@osakemyrsky-frontend/src:/app/src"
      - "./packages/@osakemyrsky-frontend/typings:/app/typings"
      - "./packages/@osakemyrsky-frontend/tailwind.config.js:/app/tailwind.config.js"
      - "./packages/@osakemyrsky-frontend/google-application-credentials.json:/tmp/keys/google-application-credentials.json"
    depends_on:
      - backend

  backend:
    container_name: osakemyrsky-backend
    build:
      context: ./packages/@osakemyrsky-backend
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      # Used for encrypting session cookies in local environment. DON'T USE IN PRODUCTION.
      IRON_PASSWORD: d33c95209c4f54cc970f187d614a5bb2d1420a7aad4ffd0946350a91a5078568
      FIRESTORE_HOST_URL: firebase-emulator
      FIRESTORE_HOST_PORT: 4040
      AUTH_GOOGLE_CLIENT_REDIRECT_URL: http://localhost:8000/auth/redirect/google
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/google-application-credentials.json
    env_file:
      - "./packages/@osakemyrsky-backend/.env"
    ports:
      - 127.0.0.1:8020:8080
    volumes:
      - "./packages/@osakemyrsky-backend/src:/app/src"
      - "./packages/@osakemyrsky-backend/typings:/app/typings"
      - "./packages/@osakemyrsky-backend/google-application-credentials.json:/tmp/keys/google-application-credentials.json"
    depends_on:
      - firebase-emulator

  firebase-emulator:
    container_name: osakemyrsky-firebase-emulator
    build:
      context: ./packages/@osakemyrsky-firebase-emulator
    restart: always
    env_file:
      - "./packages/@osakemyrsky-firebase-emulator/.env"
    ports:
      - 127.0.0.1:4000:4000
      - 127.0.0.1:4040:4040
    volumes:
      - "emulator:/firebase/.cache"

volumes:
  emulator:
    driver: local
