# For local development.

version: "3.8"

services:
  client:
    container_name: osakemyrsky-client
    build:
      context: ./packages/@osakemyrsky-client
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      API_URL: http://server:8080
    ports:
      - 127.0.0.1:8000:8080
    volumes:
      - "./packages/@osakemyrsky-client/public:/app/public"
      - "./packages/@osakemyrsky-client/styles:/app/styles"
      - "./packages/@osakemyrsky-client/src:/app/src"
      - "./packages/@osakemyrsky-client/typings:/app/typings"
      - "./packages/@osakemyrsky-client/tailwind.config.js:/app/tailwind.config\
        .js"

  server:
    container_name: osakemyrsky-server
    build:
      context: ./packages/@osakemyrsky-server
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      # Used for encrypting session cookies in local environment. DON'T USE IN PRODUCTION.
      IRON_SECRET: d33c95209c4f54cc970f187d614a5bb2d1420a7aad4ffd0946350a91a5078568
      FIRESTORE_HOST_URL: firebase-emulator
      FIRESTORE_HOST_PORT: 4040
      AUTH_GOOGLE_CLIENT_REDIRECT_URL: http://localhost:8000/auth/redirect/google
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/google-credentials.json
    env_file:
      - "./packages/@osakemyrsky-server/.env"
    ports:
      - 127.0.0.1:8020:8080
    volumes:
      - "./packages/@osakemyrsky-server/src:/app/src"
      - "./packages/@osakemyrsky-server/typings:/app/typings"
      - "./packages/@osakemyrsky-server/google-credentials.json:/tmp/keys/googl\
        e-credentials.json"
    depends_on:
      - firebase-emulator

  firebase-emulator:
    container_name: osakemyrsky-firebase-emulator
    build:
      context: ./packages/@osakemyrsky-firebase-emulator
    restart: always
    env_file:
      - "./packages/@osakemyrsky-firebase-emulator/.env"
    ports:
      - 127.0.0.1:4000:4000
      - 127.0.0.1:4040:4040
    volumes:
      - "emulator:/firebase/.cache"

volumes:
  emulator:
    driver: local
