# For local development.

version: "3.8"

services:
  client:
    container_name: osakemyrsky-client
    build:
      context: ./packages/@osakemyrsky-client
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:8090
      NEXTAUTH_URL_INTERNAL: http://localhost:8080
      NEXT_PUBLIC_APOLLO_URL: http://localhost:8095/graphql
      NEXT_PUBLIC_APOLLO_URL_INTERNAL: http://server:8080/graphql
      NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_REDIRECT_URI: http://localhost:8090/auth/callback/google
      # Private JWK for signing tokens in local environment. DON'T USE IN PRODUCTION.
      JWT_SIGNING_KEY: '{"kty":"oct","kid":"mx0g5KXY7T7ioj8AQGnhC_KWy71bYxTO1UWYAHbjyVw","alg":"HS256","k":"kPXm0uBUCH7-5NgXJ_YSkEqjgZJ87LfRSdHg4AS4Q3U"}'
    env_file:
      - "./packages/@osakemyrsky-client/.env"
    ports:
      - 127.0.0.1:8090:8080
    volumes:
      - "./packages/@osakemyrsky-client/public:/app/public"
      - "./packages/@osakemyrsky-client/styles:/app/styles"
      - "./packages/@osakemyrsky-client/src:/app/src"
      - "./packages/@osakemyrsky-client/typings:/app/typings"
      - "./packages/@osakemyrsky-client/tailwind.config.js:/app/tailwind.config\
        .js"

  server:
    container_name: osakemyrsky-server
    build:
      context: ./packages/@osakemyrsky-server
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      FIRESTORE_HOST_URL: firebase-emulator
      FIRESTORE_HOST_PORT: 8080
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/google-credentials.json
      # Private JWK for signing tokens in local environment. DON'T USE IN PRODUCTION.
      JWT_SIGNING_KEY: '{"kty":"EC","kid":"wYV089pb2dk6TpKG-LXZamIklfOQQGPIKO0BYT-Ck3s","alg":"ES256","crv":"P-256","x":"7z-tXKboXsZ1tjL-BoxgPHXaOrEgS2zzwtBMQyPUi0s","y":"z6XYL3vtbNbD9skucrPeWqpxBDX1sqslRqaQrwpPs6Y","d":"R902EY9oQk1HMr2fZmfGrSAaKuBEp_xXn4zhmTIzJ2o"}'
    env_file:
      - "./packages/@osakemyrsky-server/.env"
    ports:
      - 127.0.0.1:8095:8080
    volumes:
      - "./packages/@osakemyrsky-server/src:/app/src"
      - "./packages/@osakemyrsky-server/typings:/app/typings"
      - "./packages/@osakemyrsky-server/google-credentials.json:/tmp/keys/googl\
        e-credentials.json"
    depends_on:
      - firebase-emulator

  firebase-emulator:
    container_name: osakemyrsky-firebase-emulator
    build:
      context: ./packages/@osakemyrsky-firebase-emulator
    restart: always
    env_file:
      - "./packages/@osakemyrsky-firebase-emulator/.env"
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:4000:4000
    volumes:
      - "emulator:/firebase/.cache"

volumes:
  emulator:
    driver: local
