# For local development.

version: "3.8"

services:
  client:
    container_name: osakemyrsky-client
    build:
      context: ./packages/@osakemyrsky-client
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:8090
      NEXTAUTH_URL_INTERNAL: http://localhost:8080
      NEXT_PUBLIC_APOLLO_URL: http://localhost:8095/graphql
      NEXT_PUBLIC_APOLLO_URL_INTERNAL: http://server:8080/graphql
      NEXT_PUBLIC_GOOGLE_OAUTH_CLIENT_REDIRECT_URI: http://localhost:8090/auth/callback/google
      # Private JWK for signing tokens in local environment. DON'T USE IN PRODUCTION.
      JWT_SIGNING_KEY: '{"kty":"oct","kid":"mx0g5KXY7T7ioj8AQGnhC_KWy71bYxTO1UWYAHbjyVw","alg":"HS256","k":"kPXm0uBUCH7-5NgXJ_YSkEqjgZJ87LfRSdHg4AS4Q3U"}'
    env_file:
      - "./packages/@osakemyrsky-client/.env"
    ports:
      - 127.0.0.1:8090:8080
    volumes:
      - "./packages/@osakemyrsky-client/public:/app/public"
      - "./packages/@osakemyrsky-client/styles:/app/styles"
      - "./packages/@osakemyrsky-client/src:/app/src"
      - "./packages/@osakemyrsky-client/typings:/app/typings"
      - "./packages/@osakemyrsky-client/tailwind.config.js:/app/tailwind.config.js"

  server:
    container_name: osakemyrsky-server
    build:
      context: ./packages/@osakemyrsky-server
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      PORT: 8080
      NODE_ENV: development
      PG_CONNECTION_STRING: postgres://osakemyrsky-user:osakemyrsky-pw@database/osakemyrsky-db
      # Private JWK for signing tokens in local environment. DON'T USE IN PRODUCTION.
      JWT_SIGNING_KEY: '{"kty":"EC","kid":"wYV089pb2dk6TpKG-LXZamIklfOQQGPIKO0BYT-Ck3s","alg":"ES256","crv":"P-256","x":"7z-tXKboXsZ1tjL-BoxgPHXaOrEgS2zzwtBMQyPUi0s","y":"z6XYL3vtbNbD9skucrPeWqpxBDX1sqslRqaQrwpPs6Y","d":"R902EY9oQk1HMr2fZmfGrSAaKuBEp_xXn4zhmTIzJ2o"}'
    env_file:
      - "./packages/@osakemyrsky-server/.env"
    ports:
      - 127.0.0.1:8095:8080
    volumes:
      - "./packages/@osakemyrsky-server/src:/app/src"
      - "./packages/@osakemyrsky-server/migrations:/app/migrations"
      - "./packages/@osakemyrsky-server/typings:/app/typings"
    depends_on:
      - database

  database:
    container_name: osakemyrsky-database
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_USER: osakemyrsky-user
      POSTGRES_PASSWORD: osakemyrsky-pw
      POSTGRES_DB: osakemyrsky-db
    ports:
      - 127.0.0.1:8099:5432
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
    driver: local
