name: build
on:
  workflow_run:
    workflows:
      - "verify"
    types:
      - "completed"
    branches:
      - "master"

jobs:
  build-backend:
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_OPS_IMAGE_BUILDER_CREDENTIALS }}"
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: "368.0.0"
      - name: Submit build
        working-directory: packages/@osakemyrsky-backend
        run: |
          gcloud builds submit \
            --ignore-file=.dockerignore \
            --gcs-log-dir=gs://${{ steps.auth.outputs.project_id }}-build-logs \
            --tag=europe-west1-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/osakemyrsky/osakemyrsky-backend:$(git rev-parse --short $GITHUB_SHA)

  build-frontend:
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_OPS_IMAGE_BUILDER_CREDENTIALS }}"
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: "368.0.0"
      - name: Submit build
        working-directory: packages/@osakemyrsky-frontend
        run: |
          gcloud builds submit \
            --ignore-file=.dockerignore \
            --tag=europe-west1-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/osakemyrsky/osakemyrsky-frontend:$(git rev-parse --short $GITHUB_SHA)
